/**
 * Practice Health Report — Email sender
 * Sends PDF report as email attachment via Resend API.
 */

import { Resend } from 'resend';
import type { Recipient } from './ph-report-types';

const resend = new Resend(process.env.RESEND_API_KEY);

interface SendReportParams {
  recipients: Recipient[];
  pdfBuffer: Buffer;
  reportType: 'weekly' | 'monthly';
  periodLabel: string;
}

interface SendResult {
  sent: number;
  errors: string[];
}

export async function sendReportEmails(params: SendReportParams): Promise<SendResult> {
  const { recipients, pdfBuffer, reportType, periodLabel } = params;

  const typeLabel = reportType === 'weekly' ? 'Weekly' : 'Monthly';
  const safeLabel = periodLabel.replace(/[^a-zA-Z0-9-]/g, '-');
  const filename = `HCI-Practice-Health-${typeLabel}-${safeLabel}.pdf`;
  const subject = `${typeLabel} Practice Health Report — ${periodLabel}`;

  let sent = 0;
  const errors: string[] = [];

  for (const recipient of recipients) {
    try {
      await resend.emails.send({
        from: 'HCI Practice Health <noreply@hcimed.com>',
        to: [recipient.email],
        subject,
        html: `
          <div style="font-family: 'Source Sans Pro', Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="border-bottom: 3px solid #1B3A5C; padding-bottom: 12px; margin-bottom: 20px;">
              <h2 style="color: #1B3A5C; margin: 0;">HCI Medical Group</h2>
              <p style="color: #64748B; margin: 4px 0 0;">Practice Health Report</p>
            </div>

            <p>Dear ${recipient.full_name},</p>

            <p>Please find attached the <strong>${typeLabel.toLowerCase()} Practice Health report</strong> for <strong>${periodLabel}</strong>.</p>

            <p>This report includes:</p>
            <ul style="color: #334155;">
              <li>KPI summary with trend comparisons</li>
              <li>Visit volume and patient mix</li>
              <li>Financial performance (charges vs. collections)</li>
              <li>Payer mix breakdown</li>
              <li>Provider productivity metrics</li>
              <li>Operational indicators (no-shows, wait times, utilization)</li>
            </ul>

            <p style="color: #64748B; font-size: 13px; margin-top: 24px;">
              This is an automated report from the HCI Portal. Please contact the administrator if you have questions.
            </p>

            <hr style="border: none; border-top: 1px solid #E2E8F0; margin: 20px 0;" />

            <p style="color: #94A3B8; font-size: 11px;">
              Generated by HCI Portal &bull; Confidential — For Internal Use Only
            </p>
          </div>
        `,
        attachments: [
          {
            filename,
            content: pdfBuffer,
            contentType: 'application/pdf',
          },
        ],
      });
      sent++;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push(`Failed to send to ${recipient.email}: ${msg}`);
      console.error(`[ph-report-email] Failed to send to ${recipient.email}:`, msg);
    }
  }

  return { sent, errors };
}
